<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<RootNamespace>SiNet.Infrastructure.Autodesk</RootNamespace>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	<PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\SiNet.Application\SiNet.Application.csproj" />
	<ProjectReference Include="..\SiNet.Domain\SiNet.Domain.csproj" />
	<ProjectReference Include="..\..\..\AutodeskIntegration\SiOffice.AutodeskConnector\SiOffice.AutodeskConnector.csproj" />
  </ItemGroup>

</Project>
